/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721MetadataUpgradeable,
  IERC721MetadataUpgradeableInterface,
} from "../IERC721MetadataUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721MetadataUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721MetadataUpgradeableInterface {
    return new utils.Interface(_abi) as IERC721MetadataUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721MetadataUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC721MetadataUpgradeable;
  }
}
